/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as HiringRouteImport } from './routes/hiring'
import { Route as ChoresRouteImport } from './routes/chores'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'

const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringRoute = HiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoresRoute = ChoresRouteImport.update({
  id: '/chores',
  path: '/chores',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/calendar': typeof CalendarRoute
  '/chores': typeof ChoresRoute
  '/hiring': typeof HiringRoute
  '/kids': typeof KidsRoute
  '/meals': typeof MealsRoute
  '/pets': typeof PetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/calendar': typeof CalendarRoute
  '/chores': typeof ChoresRoute
  '/hiring': typeof HiringRoute
  '/kids': typeof KidsRoute
  '/meals': typeof MealsRoute
  '/pets': typeof PetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/calendar': typeof CalendarRoute
  '/chores': typeof ChoresRoute
  '/hiring': typeof HiringRoute
  '/kids': typeof KidsRoute
  '/meals': typeof MealsRoute
  '/pets': typeof PetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/calendar'
    | '/chores'
    | '/hiring'
    | '/kids'
    | '/meals'
    | '/pets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/calendar'
    | '/chores'
    | '/hiring'
    | '/kids'
    | '/meals'
    | '/pets'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/calendar'
    | '/chores'
    | '/hiring'
    | '/kids'
    | '/meals'
    | '/pets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CalendarRoute: typeof CalendarRoute
  ChoresRoute: typeof ChoresRoute
  HiringRoute: typeof HiringRoute
  KidsRoute: typeof KidsRoute
  MealsRoute: typeof MealsRoute
  PetsRoute: typeof PetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring': {
      id: '/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chores': {
      id: '/chores'
      path: '/chores'
      fullPath: '/chores'
      preLoaderRoute: typeof ChoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  CalendarRoute: CalendarRoute,
  ChoresRoute: ChoresRoute,
  HiringRoute: HiringRoute,
  KidsRoute: KidsRoute,
  MealsRoute: MealsRoute,
  PetsRoute: PetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
